---
title: "Intro Tidymodels"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}
library(rmarkdown)
library(flexdashboard)
library(tidyverse)
library(tidymodels)
library(pROC)
library(vip)


# mini_olist <- tbl(con, "OLIST_ABT") %>%
#   select(data_ref, seller_id, fl_venda, proporcao_ativacao_meses,
#          qtd_pedidos_ate_hoje, tend_pedidos_m1_m3, tend_pedidos_m1_m6,
#          media_dias_entre_dt_compra_dt_entrega_ate_hoje,
#          media_vlr_pedido_ultimo_mes, tend_notas_review_m1_m3,
#          media_dias_entre_dt_compra_dt_entrega_ate_hoje) %>%
#   collect() %>%
#   group_by(fl_venda) %>%
#   sample_frac(0.1)
```


PASSO 0) Importação 
=============

Column
-------------------
### Importação do SQL

```{r, echo=TRUE}
library(DBI)
zip::unzip("olist.zip")

# Abre conexão com o banco
con <- dbConnect(RSQLite::SQLite(), "olist.db")
dbListTables(con)
mini_olist <- tbl(con, "mini_olist")
glimpse(mini_olist)
```

### PASSO 1) Resumão

```{r}
skimr::skim(mini_olist)
```

